apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 7
  selector:
    app: proxy
  template:
    metadata:
      name: nginx
      labels:
        app: proxy
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
