apiVersion: v1
kind: Pod
metadata:
  name: voldemo
  labels:
    name: voldemo
spec:
  volumes:
    - name: voldemo
      emptDir:{}
  containers:
  - name: volemo
    image: kammana/nodeapp:v1
    volumeMounts:
      - name: voldemo
        mountPath: /var/logs
